"""Deterministic investigation preparation workflow."""

from collections import Counter
from datetime import UTC, datetime

from .models import InvestigationRequest, InvestigationResponse


class InvestigationWorkflow:
    """Prepare a citation-complete investigation envelope without inventing findings.

    Provider orchestration can consume this envelope later. Until then, the
    deterministic workflow reports what evidence is available and leaves
    hypotheses empty rather than manufacturing conclusions.
    """

    def investigate(self, request: InvestigationRequest) -> InvestigationResponse:
        evidence_counts = Counter(item.reference_type for item in request.evidence)
        evidence_summary = ", ".join(
            f"{count} {evidence_type.replace('_', ' ')}"
            for evidence_type, count in sorted(evidence_counts.items())
        )
        summary = (
            f"Investigation prepared for incident {request.incident_id} using "
            f"{len(request.evidence)} evidence reference(s): {evidence_summary}. "
            "No hypothesis was generated by the deterministic workflow."
        )
        return InvestigationResponse(
            incident_id=request.incident_id,
            summary=summary,
            hypotheses=(),
            cited_evidence=request.evidence,
            generated_at=datetime.now(UTC),
        )
